version: '3'

services:
  application:
    build: .
    volumes:
      - ./temp:/temp # This is mounting a local directory onto Docker. Moint additional volumes as required
    depends_on:
          - "database"

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: retail
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - "9906:3306"
